export const FETCH_INITIAL_TRACKS = "FETCH_INITIAL_TRACKS";
export const FETCH_INITIAL_TRACKS_ERROR = "FETCH_INITIAL_TRACKS_ERROR";
export const FETCH_INITIAL_TRACKS_SUCCESS = "FETCH_INITIAL_TRACKS_SUCCESS";
